export const wordList = [
    // 1. Kategória: Állatok
    { category: "Állatok", secretWord: "KUTYA", hint: "UGATÁS" },
    { category: "Állatok", secretWord: "MACSKA", hint: "DOROMBOLÁS" },
    { category: "Állatok", secretWord: "LÓ", hint: "NYEREG" },
    { category: "Állatok", secretWord: "ELEFÁNT", hint: "ORMÁNY" },
    { category: "Állatok", secretWord: "OROSZLÁN", hint: "SÖRÉNY" },
    { category: "Állatok", secretWord: "TIGRIS", hint: "CSÍKOS" },
    { category: "Állatok", secretWord: "ZSIRÁF", hint: "HOSSZÚ NYAK" },
    { category: "Állatok", secretWord: "KÍGYÓ", hint: "SZISZEGÉS" },
    { category: "Állatok", secretWord: "BÉKA", hint: "BREKEGÉS" },
    { category: "Állatok", secretWord: "MEDVE", hint: "MÉZ" },
    { category: "Állatok", secretWord: "FARKAS", hint: "VONYÍTÁS" },
    { category: "Állatok", secretWord: "NYÚL", hint: "RÉPA" },
    { category: "Állatok", secretWord: "RÓKA", hint: "RAVASZ" },
    { category: "Állatok", secretWord: "MAJOM", hint: "BANÁN" },
    { category: "Állatok", secretWord: "CÁPA", hint: "USZONY" },
    { category: "Állatok", secretWord: "BÁLNA", hint: "HATALMAS" },
    { category: "Állatok", secretWord: "PINGVIN", hint: "JÉG" },
    { category: "Állatok", secretWord: "TEKNŐS", hint: "PÁNCÉL" },
    { category: "Állatok", secretWord: "DISZNÓ", hint: "MALAC" },
    { category: "Állatok", secretWord: "BÁRÁNY", hint: "GYAPJÚ" },

    // 2. Kategória: Mindennapi tárgyak
    { category: "Mindennapi tárgyak", secretWord: "KULCS", hint: "ZÁR" },
    { category: "Mindennapi tárgyak", secretWord: "OLLÓ", hint: "VÁGÁS" },
    { category: "Mindennapi tárgyak", secretWord: "KALAPÁCS", hint: "SZÖG" },
    { category: "Mindennapi tárgyak", secretWord: "ÓRA", hint: "IDŐ" },
    { category: "Mindennapi tárgyak", secretWord: "TÜKÖR", hint: "TÜKRÖZŐDÉS" },
    { category: "Mindennapi tárgyak", secretWord: "FÉSŰ", hint: "HAJ" },
    { category: "Mindennapi tárgyak", secretWord: "SZAPPAN", hint: "MOSAKODÁS" },
    { category: "Mindennapi tárgyak", secretWord: "TÖRÜLKÖZŐ", hint: "SZÁRÍTKOZÁS" },
    { category: "Mindennapi tárgyak", secretWord: "ESERNYŐ", hint: "ESŐ" },
    { category: "Mindennapi tárgyak", secretWord: "PÉNZTÁRCA", hint: "KÉSZPÉNZ" },
    { category: "Mindennapi tárgyak", secretWord: "SZEMÜVEG", hint: "LÁTÁS" },
    { category: "Mindennapi tárgyak", secretWord: "ZSEBKENDŐ", hint: "ORRFÚJÁS" },
    { category: "Mindennapi tárgyak", secretWord: "GYÚJTSÓ", hint: "TŰZ" },
    { category: "Mindennapi tárgyak", secretWord: "ELEM", hint: "ENERGIA" },
    { category: "Mindennapi tárgyak", secretWord: "RAGASZTÓ", hint: "PAPÍR" },
    { category: "Mindennapi tárgyak", secretWord: "FOGKEFE", hint: "FOGKRÉM" },
    { category: "Mindennapi tárgyak", secretWord: "WC-PAPÍR", hint: "MOSDÓ" },
    { category: "Mindennapi tárgyak", secretWord: "KUKA", hint: "SZEMÉT" },
    { category: "Mindennapi tárgyak", secretWord: "SEBTEPASZ", hint: "VÉRZÉS" },
    { category: "Mindennapi tárgyak", secretWord: "CSOMAGOLÓPAPÍR", hint: "AJÁNDÉK" },

    // 3. Kategória: Étel és ital
    { category: "Étel és ital", secretWord: "KENYÉR", hint: "PÉKSÉG" },
    { category: "Étel és ital", secretWord: "TEJ", hint: "FEHÉR" },
    { category: "Étel és ital", secretWord: "SAJT", hint: "EGÉR" },
    { category: "Étel és ital", secretWord: "LEVES", hint: "TÁNYÉR" },
    { category: "Étel és ital", secretWord: "PIZZA", hint: "OLASZ" },
    { category: "Étel és ital", secretWord: "HAMBURGER", hint: "GYORSÉTTEREM" },
    { category: "Étel és ital", secretWord: "FAGYLALT", hint: "HIDEG" },
    { category: "Étel és ital", secretWord: "CSOKOLÁDÉ", hint: "ÉDES" },
    { category: "Étel és ital", secretWord: "VÍZ", hint: "CSAP" },
    { category: "Étel és ital", secretWord: "SÖR", hint: "HABOS" },
    { category: "Étel és ital", secretWord: "BOR", hint: "SZŐLŐ" },
    { category: "Étel és ital", secretWord: "TEA", hint: "FORRÓ" },
    { category: "Étel és ital", secretWord: "HÚS", hint: "MÉSZÁROS" },
    { category: "Étel és ital", secretWord: "TOJÁS", hint: "TYÚK" },
    { category: "Étel és ital", secretWord: "VAJ", hint: "KENÉS" },
    { category: "Étel és ital", secretWord: "SÓ", hint: "SÓS" },
    { category: "Étel és ital", secretWord: "CUKOR", hint: "KÁVÉBA" },
    { category: "Étel és ital", secretWord: "TÉSZTA", hint: "SPAGETTI" },
    { category: "Étel és ital", secretWord: "MÉZ", hint: "MÉH" },
    { category: "Étel és ital", secretWord: "KOLBÁSZ", hint: "SERTÉS" },

    // 4. Kategória: Iskola
    { category: "Iskola", secretWord: "CERUZA", hint: "GRAFIT" },
    { category: "Iskola", secretWord: "TOLL", hint: "TINTA" },
    { category: "Iskola", secretWord: "RADÍR", hint: "TÖRLÉS" },
    { category: "Iskola", secretWord: "FÜZET", hint: "VONALAS" },
    { category: "Iskola", secretWord: "VONALZÓ", hint: "MÉRÉS" },
    { category: "Iskola", secretWord: "TANÁR", hint: "OKTATÁS" },
    { category: "Iskola", secretWord: "DIÁK", hint: "TANULÁS" },
    { category: "Iskola", secretWord: "SZÜNET", hint: "CSENGŐ" },
    { category: "Iskola", secretWord: "HÁZIFELADAT", hint: "OTTHONI" },
    { category: "Iskola", secretWord: "TÖRTÉNELEM", hint: "MÚLT" },
    { category: "Iskola", secretWord: "MATEMATIKA", hint: "SZÁMOK" },
    { category: "Iskola", secretWord: "TORNATEREM", hint: "TESI" },
    { category: "Iskola", secretWord: "KRÉTA", hint: "POROS" },
    { category: "Iskola", secretWord: "BIZONYÍTVÁNY", hint: "JEGYEK" },
    { category: "Iskola", secretWord: "FÖLDRAJZ", hint: "TÉRKÉP" },
    { category: "Iskola", secretWord: "PAD", hint: "ÜLÉS" },
    { category: "Iskola", secretWord: "HEGYEZŐ", hint: "FORGÁCS" },
    { category: "Iskola", secretWord: "NAPLÓ", hint: "HIÁNYZÁS" },
    { category: "Iskola", secretWord: "TOLLTARTÓ", hint: "CÍZÁR" },
    { category: "Iskola", secretWord: "IRODALOM", hint: "VERSEK" },

    // 5. Kategória: Járművek
    { category: "Járművek", secretWord: "AUTÓ", hint: "NÉGY KERÉK" },
    { category: "Járművek", secretWord: "BICIKLI", hint: "PEDÁL" },
    { category: "Járművek", secretWord: "MOTOR", hint: "BUKÓSISAK" },
    { category: "Járművek", secretWord: "BUSZ", hint: "JEGY" },
    { category: "Járművek", secretWord: "VONAT", hint: "SÍN" },
    { category: "Járművek", secretWord: "REPÜLŐ", hint: "ÉG" },
    { category: "Járművek", secretWord: "HAJÓ", hint: "VÍZ" },
    { category: "Járművek", secretWord: "HELIKOPTER", hint: "ROTOR" },
    { category: "Járművek", secretWord: "KAMION", hint: "TEHER" },
    { category: "Járművek", secretWord: "TRAKTOR", hint: "SZÁNTÁS" },
    { category: "Járművek", secretWord: "TENGERALATTJÓ", hint: "MÉLYSÉG" },
    { category: "Járművek", secretWord: "VILLAMOS", hint: "VÁROSI KÖZLEKEDÉS" },
    { category: "Járművek", secretWord: "METRÓ", hint: "FÖLDALATTI" },
    { category: "Járművek", secretWord: "ROLLER", hint: "LÖKÉS" },
    { category: "Járművek", secretWord: "SZEKÉR", hint: "LÓHÚZTA" },
    { category: "Járművek", secretWord: "MENTŐAUTÓ", hint: "SZIRÉNA" },
    { category: "Járművek", secretWord: "TŰZOLTÓAUTÓ", hint: "PIROS" },
    { category: "Járművek", secretWord: "RENDŐRAUTÓ", hint: "VILLOGÓ" },
    { category: "Járművek", secretWord: "ŰRHAJÓ", hint: "CSILLAGOK" },
    { category: "Járművek", secretWord: "CSONAK", hint: "EVEZŐ" },

    // 6. Kategória: Szakmák
    { category: "Szakmák", secretWord: "ORVOS", hint: "GYÓGYÍTÁS" },
    { category: "Szakmák", secretWord: "RENDŐR", hint: "TÖRVÉNY" },
    { category: "Szakmák", secretWord: "TŰZOLTÓ", hint: "LÁNGOK" },
    { category: "Szakmák", secretWord: "SZAKÁCS", hint: "ÉTTEREM" },
    { category: "Szakmák", secretWord: "PINCÉR", hint: "FELSZOLGÁLÁS" },
    { category: "Szakmák", secretWord: "ÉPÍTÉSZ", hint: "TERVEZÉS" },
    { category: "Szakmák", secretWord: "FOTÓS", hint: "KAMERA" },
    { category: "Szakmák", secretWord: "ZENÉSZ", hint: "KONCERT" },
    { category: "Szakmák", secretWord: "SZÍNÉSZ", hint: "FILM" },
    { category: "Szakmák", secretWord: "ÍRÓ", hint: "REGÉNY" },
    { category: "Szakmák", secretWord: "FESTŐ", hint: "VÁSZON" },
    { category: "Szakmák", secretWord: "INFORMATIKUS", hint: "KÓDOLÁS" },
    { category: "Szakmák", secretWord: "FODRÁSZ", hint: "HAJVÁGÁS" },
    { category: "Szakmák", secretWord: "SOFŐR", hint: "VEZETÉS" },
    { category: "Szakmák", secretWord: "ÜGYVÉD", hint: "BÍRÓSÁG" },
    { category: "Szakmák", secretWord: "PILÓTA", hint: "REPÜLÉS" },
    { category: "Szakmák", secretWord: "ÁCS", hint: "FAANYAG" },
    { category: "Szakmák", secretWord: "KERTÉSZ", hint: "NÖVÉNYEK" },
    { category: "Szakmák", secretWord: "FOGORVOS", hint: "LYUKAS FOG" },
    { category: "Szakmák", secretWord: "BÍRÓ", hint: "KALAPÁCS" },

    // 7. Kategória: Természet
    { category: "Természet", secretWord: "FA", hint: "TÖRZSE VAN" },
    { category: "Természet", secretWord: "VIRÁG", hint: "SZIROM" },
    { category: "Természet", secretWord: "FŰ", hint: "ZÖLD" },
    { category: "Természet", secretWord: "HEGY", hint: "CSÚCS" },
    { category: "Természet", secretWord: "VÖLGY", hint: "MÉLY" },
    { category: "Természet", secretWord: "FOLYÓ", hint: "ÁRAMLÁS" },
    { category: "Természet", secretWord: "TÓ", hint: "ÁLLÓVÍZ" },
    { category: "Természet", secretWord: "TENGER", hint: "SÓS" },
    { category: "Természet", secretWord: "ÓCEÁN", hint: "LEGNAGYOBB" },
    { category: "Természet", secretWord: "SZIGET", hint: "KÖRÜLVESZI A VÍZ" },
    { category: "Természet", secretWord: "SIVATAG", hint: "HOMOK" },
    { category: "Természet", secretWord: "DZSUNGEL", hint: "TRÓPUSI" },
    { category: "Természet", secretWord: "BARLANG", hint: "SÖTÉT" },
    { category: "Természet", secretWord: "FELHŐ", hint: "ÉG" },
    { category: "Természet", secretWord: "NAP", hint: "SUGÁR" },
    { category: "Természet", secretWord: "HOLD", hint: "ÉJSZAKA" },
    { category: "Természet", secretWord: "CSILLAG", hint: "FÉNYES" },
    { category: "Természet", secretWord: "SZÉL", hint: "FÚJÁS" },
    { category: "Természet", secretWord: "ESŐ", hint: "VÍZCSEPP" },
    { category: "Természet", secretWord: "HÓ", hint: "PEHELY" },

    // 8. Kategória: Sport
    { category: "Sport", secretWord: "FUTBALL", hint: "GÓL" },
    { category: "Sport", secretWord: "KOSÁRLABDA", hint: "PALÁNK" },
    { category: "Sport", secretWord: "TENISZ", hint: "ÜTŐ" },
    { category: "Sport", secretWord: "ÚSZÁS", hint: "MEDENCE" },
    { category: "Sport", secretWord: "FUTÁS", hint: "MARATON" },
    { category: "Sport", secretWord: "KERÉKPÁROZÁS", hint: "TOUR DE FRANCE" },
    { category: "Sport", secretWord: "SÍELÉS", hint: "HÓ" },
    { category: "Sport", secretWord: "KORCSOLYA", hint: "JÉG" },
    { category: "Sport", secretWord: "BOKSZ", hint: "KESZTYŰ" },
    { category: "Sport", secretWord: "BIRKÓZÁS", hint: "SZŐNYEG" },
    { category: "Sport", secretWord: "RÖPLABDA", hint: "HÁLÓ" },
    { category: "Sport", secretWord: "KÉZILABDA", hint: "HETES" },
    { category: "Sport", secretWord: "VÍZILABDA", hint: "SAPKA" },
    { category: "Sport", secretWord: "GOLF", hint: "LYUK" },
    { category: "Sport", secretWord: "BASEBALL", hint: "HAZAIFUTÁS" },
    { category: "Sport", secretWord: "JÉGKORONG", hint: "KORONG" },
    { category: "Sport", secretWord: "LOVAGLÁS", hint: "AKADÁLY" },
    { category: "Sport", secretWord: "TORNA", hint: "GYŰRŰ" },
    { category: "Sport", secretWord: "VÍVÁS", hint: "KARD" },
    { category: "Sport", secretWord: "SAKK", hint: "MATT" },

    // 9. Kategória: Ruházat
    { category: "Ruházat", secretWord: "PÓLÓ", hint: "RÖVID UJJÚ" },
    { category: "Ruházat", secretWord: "ING", hint: "GALLÉR" },
    { category: "Ruházat", secretWord: "NADRÁG", hint: "FARMER" },
    { category: "Ruházat", secretWord: "SZOKNYA", hint: "LÁNYOK" },
    { category: "Ruházat", secretWord: "RUHA", hint: "ELEGÁNS" },
    { category: "Ruházat", secretWord: "PULÓVER", hint: "MELEG" },
    { category: "Ruházat", secretWord: "KABÁT", hint: "TÉLI" },
    { category: "Ruházat", secretWord: "SAPKA", hint: "FEJ" },
    { category: "Ruházat", secretWord: "SÁL", hint: "NYAK" },
    { category: "Ruházat", secretWord: "KESZTYŰ", hint: "KÉZ" },
    { category: "Ruházat", secretWord: "ZOKNI", hint: "LÁBFEJ" },
    { category: "Ruházat", secretWord: "CIPŐ", hint: "FŰZŐ" },
    { category: "Ruházat", secretWord: "CSIZMA", hint: "HÓBAN" },
    { category: "Ruházat", secretWord: "SZANDÁL", hint: "NYÁRI" },
    { category: "Ruházat", secretWord: "PAPUCS", hint: "STRAND" },
    { category: "Ruházat", secretWord: "FÜRDŐRUHA", hint: "ÚSZÁS" },
    { category: "Ruházat", secretWord: "NYAKKENDŐ", hint: "ÖLTÖNY" },
    { category: "Ruházat", secretWord: "ÖV", hint: "DERÉK" },
    { category: "Ruházat", secretWord: "ALSÓNADRÁG", hint: "FEHÉRNEMŰ" },
    { category: "Ruházat", secretWord: "MELEGÍTŐ", hint: "KÉNYELMES" },

    // 10. Kategória: Testrészek
    { category: "Testrészek", secretWord: "FEJ", hint: "AGY" },
    { category: "Testrészek", secretWord: "SZEM", hint: "LÁTÁS" },
    { category: "Testrészek", secretWord: "FÜL", hint: "HALLÁS" },
    { category: "Testrészek", secretWord: "ORR", hint: "SZAGLÁS" },
    { category: "Testrészek", secretWord: "SZÁJ", hint: "BESZÉD" },
    { category: "Testrészek", secretWord: "FOG", hint: "RÁGÁS" },
    { category: "Testrészek", secretWord: "NYELV", hint: "ÍZLELÉS" },
    { category: "Testrészek", secretWord: "NYAK", hint: "TOROK" },
    { category: "Testrészek", secretWord: "VÁLL", hint: "TEHER" },
    { category: "Testrészek", secretWord: "KAR", hint: "IZOM" },
    { category: "Testrészek", secretWord: "KÉZ", hint: "TENYÉR" },
    { category: "Testrészek", secretWord: "UJJ", hint: "KÖRÖM" },
    { category: "Testrészek", secretWord: "MELLKAS", hint: "SZÍV" },
    { category: "Testrészek", secretWord: "HAS", hint: "KÖLDÖK" },
    { category: "Testrészek", secretWord: "HÁT", hint: "GERINC" },
    { category: "Testrészek", secretWord: "LÁB", hint: "COMB" },
    { category: "Testrészek", secretWord: "TÉRD", hint: "HAJLÍTÁS" },
    { category: "Testrészek", secretWord: "BOKA", hint: "FICAM" },
    { category: "Testrészek", secretWord: "SAROK", hint: "ACHILLES" },
    { category: "Testrészek", secretWord: "TALP", hint: "LÚD" },

    // 11. Kategória: Bútorok és Otthon
    { category: "Bútorok és Otthon", secretWord: "ASZTAL", hint: "ÉTKEZÉS" },
    { category: "Bútorok és Otthon", secretWord: "SZÉK", hint: "TÁMLA" },
    { category: "Bútorok és Otthon", secretWord: "KANAPÉ", hint: "NAPPALI" },
    { category: "Bútorok és Otthon", secretWord: "ÁGY", hint: "ALVÁS" },
    { category: "Bútorok és Otthon", secretWord: "SZEKRÉNY", hint: "RUHÁK" },
    { category: "Bútorok és Otthon", secretWord: "POLC", hint: "KÖNYVEK" },
    { category: "Bútorok és Otthon", secretWord: "KOMÓD", hint: "FIÓKOS" },
    { category: "Bútorok és Otthon", secretWord: "FOTEL", hint: "KÉNYELEM" },
    { category: "Bútorok és Otthon", secretWord: "LÁMPA", hint: "ÉJJELISZEKRÉNY" },
    { category: "Bútorok és Otthon", secretWord: "SZŐNYEG", hint: "PADLÓ" },
    { category: "Bútorok és Otthon", secretWord: "FÜGGÖNY", hint: "ABLAK" },
    { category: "Bútorok és Otthon", secretWord: "FESTMÉNY", hint: "FALON" },
    { category: "Bútorok és Otthon", secretWord: "TV", hint: "TÁVIRÁNYÍTÓ" },
    { category: "Bútorok és Otthon", secretWord: "VÁZA", hint: "VIRÁGNAK" },
    { category: "Bútorok és Otthon", secretWord: "PÁRNA", hint: "PUHA" },
    { category: "Bútorok és Otthon", secretWord: "TAKARÓ", hint: "MELEGÍT" },
    { category: "Bútorok és Otthon", secretWord: "MATRAC", hint: "ÁGYON" },
    { category: "Bútorok és Otthon", secretWord: "FÜRDŐKÁD", hint: "HABFÜRDŐ" },
    { category: "Bútorok és Otthon", secretWord: "ZUHANYZÓ", hint: "VÍZSUGÁR" },
    { category: "Bútorok és Otthon", secretWord: "MOSDÓKAGYLÓ", hint: "KÉZMOSÁS" },

    // 12. Kategória: Technológia
    { category: "Technológia", secretWord: "SZÁMÍTÓGÉP", hint: "MONITOR" },
    { category: "Technológia", secretWord: "TELEFON", hint: "MOBIL" },
    { category: "Technológia", secretWord: "TABLET", hint: "ÉRINTŐKÉPERNYŐ" },
    { category: "Technológia", secretWord: "TELEVÍZIÓ", hint: "CSATORNÁK" },
    { category: "Technológia", secretWord: "RÁDIÓ", hint: "FREKVENCIA" },
    { category: "Technológia", secretWord: "FÉNYKÉPEZŐGÉP", hint: "VAKU" },
    { category: "Technológia", secretWord: "KAMERA", hint: "FELVÉTEL" },
    { category: "Technológia", secretWord: "NYOMTATÓ", hint: "PAPÍR" },
    { category: "Technológia", secretWord: "HANGSZÓRÓ", hint: "HANGERŐ" },
    { category: "Technológia", secretWord: "FÜLHALLGATÓ", hint: "ZENE" },
    { category: "Technológia", secretWord: "OKOSÓRA", hint: "CSUKLÓ" },
    { category: "Technológia", secretWord: "LAPTOP", hint: "HORDOZHATÓ" },
    { category: "Technológia", secretWord: "TÖLTŐ", hint: "AKKUMULÁTOR" },
    { category: "Technológia", secretWord: "MIKROHULLÁMÚ", hint: "MELEGÍTÉS" },
    { category: "Technológia", secretWord: "HŰTŐSZEKRÉNY", hint: "FAGYASZTÓ" },
    { category: "Technológia", secretWord: "MOSÓGÉP", hint: "CENTRIFUGA" },
    { category: "Technológia", secretWord: "PORSZÍVÓ", hint: "TAKARÍTÁS" },
    { category: "Technológia", secretWord: "VASALÓ", hint: "GYŰRÖDÉS" },
    { category: "Technológia", secretWord: "ROUTER", hint: "WIFI" },
    { category: "Technológia", secretWord: "DRÓN", hint: "LÉGI FOTÓ" },

    // 13. Kategória: Hangszerek
    { category: "Hangszerek", secretWord: "ZONGORA", hint: "FEKETE-FEHÉR BILLENTYŰK" },
    { category: "Hangszerek", secretWord: "GITÁR", hint: "HATHÚROS" },
    { category: "Hangszerek", secretWord: "HEGEDŰ", hint: "VONÓ" },
    { category: "Hangszerek", secretWord: "DOB", hint: "ÜTŐS" },
    { category: "Hangszerek", secretWord: "FUVOLA", hint: "FÚVÓS" },
    { category: "Hangszerek", secretWord: "TROMBITA", hint: "RÉZ" },
    { category: "Hangszerek", secretWord: "HARSONA", hint: "HÚZÓKA" },
    { category: "Hangszerek", secretWord: "KLARINÉT", hint: "FEKETE FAFÚVÓS" },
    { category: "Hangszerek", secretWord: "SZAXOFON", hint: "JAZZ" },
    { category: "Hangszerek", secretWord: "HÁRFA", hint: "ANGYALOK" },
    { category: "Hangszerek", secretWord: "CIMBALOM", hint: "VERŐK" },
    { category: "Hangszerek", secretWord: "HARMONIKA", hint: "HARANGLÁB" },
    { category: "Hangszerek", secretWord: "CSELLÓ", hint: "NAGY HEGEDŰ" },
    { category: "Hangszerek", secretWord: "NAGYBŐGŐ", hint: "LEGMÉLYEBB" },
    { category: "Hangszerek", secretWord: "XILOFON", hint: "FALAPOK" },
    { category: "Hangszerek", secretWord: "FURULYA", hint: "MŰANYAG ISKOLAI" },
    { category: "Hangszerek", secretWord: "BENDZSÓ", hint: "COUNTRY" },
    { category: "Hangszerek", secretWord: "UKULELE", hint: "HAWAII" },
    { category: "Hangszerek", secretWord: "SZINTETIZÁTOR", hint: "ELEKTROMOS" },
    { category: "Hangszerek", secretWord: "LANT", hint: "KÖZÉPKOR" },

    // 14. Kategória: Konyha
    { category: "Konyha", secretWord: "FAZÉK", hint: "FŐZÉS" },
    { category: "Konyha", secretWord: "SERPENYŐ", hint: "SÜTÉS" },
    { category: "Konyha", secretWord: "KÉS", hint: "ÉLES" },
    { category: "Konyha", secretWord: "VILLA", hint: "SZÚRÁS" },
    { category: "Konyha", secretWord: "KANÁL", hint: "MERÍTÉS" },
    { category: "Konyha", secretWord: "TÁNYÉR", hint: "PORCELÁN" },
    { category: "Konyha", secretWord: "POHÁR", hint: "ÜVEG" },
    { category: "Konyha", secretWord: "BÖGRE", hint: "FÜLES" },
    { category: "Konyha", secretWord: "KANCSÓ", hint: "KIÖNTŐ" },
    { category: "Konyha", secretWord: "VÁGÓDESZKA", hint: "FAALAP" },
    { category: "Konyha", secretWord: "RESZELŐ", hint: "SAJTHOZ" },
    { category: "Konyha", secretWord: "MERŐKANÁL", hint: "NAGY KANÁL" },
    { category: "Konyha", secretWord: "DUGÓHÚZÓ", hint: "BOROSÜVEG" },
    { category: "Konyha", secretWord: "SZITA", hint: "LISZT" },
    { category: "Konyha", secretWord: "HABVERŐ", hint: "TOJÁSHAB" },
    { category: "Konyha", secretWord: "NYÚJTÓFA", hint: "TÉSZTA" },
    { category: "Konyha", secretWord: "TÁL", hint: "MÉLY" },
    { category: "Konyha", secretWord: "TÖLCSÉR", hint: "ÁTTÖLTÉS" },
    { category: "Konyha", secretWord: "SÜTŐ", hint: "TEPSI" },
    { category: "Konyha", secretWord: "BOGRÁCS", hint: "KINTI TŰZ" },

    // 15. Kategória: Növények
    { category: "Növények", secretWord: "RÓZSA", hint: "TÖVIS" },
    { category: "Növények", secretWord: "TULIPÁN", hint: "HOLLANDIA" },
    { category: "Növények", secretWord: "NAPRAFORGÓ", hint: "MAG" },
    { category: "Növények", secretWord: "FENYŐ", hint: "KARÁCSONYFA" },
    { category: "Növények", secretWord: "TÖLGY", hint: "MAKK" },
    { category: "Növények", secretWord: "BÚZA", hint: "LISZT" },
    { category: "Növények", secretWord: "KUKORICA", hint: "CSŐ" },
    { category: "Növények", secretWord: "KAKTUSZ", hint: "SIVATAG" },
    { category: "Növények", secretWord: "PÁLMAFA", hint: "KÓKUSZ" },
    { category: "Növények", secretWord: "ORCHIDEA", hint: "EGZOTIKUS" },
    { category: "Növények", secretWord: "LEVENDULA", hint: "ILLATOS LILA" },
    { category: "Növények", secretWord: "MOHA", hint: "FÁK ÉSZAKI OLDALA" },
    { category: "Növények", secretWord: "GOMBA", hint: "KALAP" },
    { category: "Növények", secretWord: "SZŐLŐ", hint: "INDA" },
    { category: "Növények", secretWord: "ALMAFA", hint: "GYÜMÖLCSÖS" },
    { category: "Növények", secretWord: "DIÓFA", hint: "CSONTHÉJAS" },
    { category: "Növények", secretWord: "BOKOR", hint: "CSERJE" },
    { category: "Növények", secretWord: "PITYPANG", hint: "ELFÚJHATÓ" },
    { category: "Növények", secretWord: "HÓVIRÁG", hint: "TAVASZ HÍRNÖKE" },
    { category: "Növények", secretWord: "BAMBUSZ", hint: "PANDA" },

    // 16. Kategória: Épületek és Helyszínek
    { category: "Épületek és Helyszínek", secretWord: "HÁZ", hint: "KEMENCE" },
    { category: "Épületek és Helyszínek", secretWord: "LAKÁS", hint: "TÁRSASHÁZ" },
    { category: "Épületek és Helyszínek", secretWord: "KÓRHÁZ", hint: "BETEGEK" },
    { category: "Épületek és Helyszínek", secretWord: "ÉTTEREM", hint: "MENÜ" },
    { category: "Épületek és Helyszínek", secretWord: "SZÁLLODA", hint: "RECEPCIÓ" },
    { category: "Épületek és Helyszínek", secretWord: "BOLT", hint: "VÁSÁRLÁS" },
    { category: "Épületek és Helyszínek", secretWord: "PLÁZA", hint: "BEVÁSÁRLÓKÖZPONT" },
    { category: "Épületek és Helyszínek", secretWord: "MOZI", hint: "POPCORN" },
    { category: "Épületek és Helyszínek", secretWord: "SZÍNHÁZ", hint: "FÜGGÖNY" },
    { category: "Épületek és Helyszínek", secretWord: "MÚZEUM", hint: "TÁRLAT" },
    { category: "Épületek és Helyszínek", secretWord: "KÖNYVTÁR", hint: "CSENDBEN" },
    { category: "Épületek és Helyszínek", secretWord: "TEMPLOM", hint: "HARANG" },
    { category: "Épületek és Helyszínek", secretWord: "VÁR", hint: "BÁSTYA" },
    { category: "Épületek és Helyszínek", secretWord: "KASTÉLY", hint: "KIRÁLYI" },
    { category: "Épületek és Helyszínek", secretWord: "GYÁR", hint: "KÉMÉNY" },
    { category: "Épületek és Helyszínek", secretWord: "IRODA", hint: "ÍRÓASZTALOK" },
    { category: "Épületek és Helyszínek", secretWord: "ÁLLOMÁS", hint: "PERON" },
    { category: "Épületek és Helyszínek", secretWord: "REPÜLŐTÉR", hint: "TERMINÁL" },
    { category: "Épületek és Helyszínek", secretWord: "PARK", hint: "SÉTA" },
    { category: "Épületek és Helyszínek", secretWord: "STADION", hint: "LELÁTÓ" },

    // 17. Kategória: Zöldségek és Gyümölcsök
    { category: "Zöldségek és Gyümölcsök", secretWord: "PARADICSOM", hint: "PIROS" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "PAPRIKA", hint: "CSÍPŐS" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "HAGYMA", hint: "SÍRÁS" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "FOKHAGYMA", hint: "VÁMPÍR" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "RÉPA", hint: "NARANCSSÁRGA" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "BURGONYA", hint: "KRUMPLI" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "KÁPOSZTA", hint: "TÖLTÖTT" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "SALÁTA", hint: "FEJES" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "UBORKA", hint: "KOVÁSZOS" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "BORSÓ", hint: "HÜVELY" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "ALMA", hint: "HÓFEHÉRKE" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "KÖRTE", hint: "ALAKÚ" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "SZILVA", hint: "LEKVÁR" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "BARACK", hint: "MAG" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "CSERESZNYE", hint: "PÁROS" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "MEGGY", hint: "SAVANYKÁS" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "EPER", hint: "MAGOCSKÁK KÍVÜL" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "MÁLNA", hint: "BOKRON TEREM" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "DINNYE", hint: "GÖRÖG VAGY SÁRGA" },
    { category: "Zöldségek és Gyümölcsök", secretWord: "CITROM", hint: "FANYAR" },

    // 18. Kategória: Színek és Formák
    { category: "Színek és Formák", secretWord: "PIROS", hint: "VÉR" },
    { category: "Színek és Formák", secretWord: "KÉK", hint: "ÉG" },
    { category: "Színek és Formák", secretWord: "ZÖLD", hint: "FŰ" },
    { category: "Színek és Formák", secretWord: "SÁRGA", hint: "NAP" },
    { category: "Színek és Formák", secretWord: "FEHÉR", hint: "HÓ" },
    { category: "Színek és Formák", secretWord: "FEKETE", hint: "SÖTÉT" },
    { category: "Színek és Formák", secretWord: "BARNA", hint: "FÖLD" },
    { category: "Színek és Formák", secretWord: "LILA", hint: "MILKA" },
    { category: "Színek és Formák", secretWord: "RÓZSASZÍN", hint: "LÁNYOS" },
    { category: "Színek és Formák", secretWord: "NARANCSSÁRGA", hint: "RÉPA SZÍNE" },
    { category: "Színek és Formák", secretWord: "SZÜRKE", hint: "EGÉR" },
    { category: "Színek és Formák", secretWord: "KÖR", hint: "KARIKA" },
    { category: "Színek és Formák", secretWord: "NÉGYZET", hint: "KOCKA OLDALA" },
    { category: "Színek és Formák", secretWord: "HÁROMSZÖG", hint: "PIRAMIS" },
    { category: "Színek és Formák", secretWord: "TÉGLALAP", hint: "AJTÓ FORMA" },
    { category: "Színek és Formák", secretWord: "OVÁLIS", hint: "TOJÁS" },
    { category: "Színek és Formák", secretWord: "CSILLAG", hint: "ÉGEN" },
    { category: "Színek és Formák", secretWord: "SZÍV", hint: "SZERELEM" },
    { category: "Színek és Formák", secretWord: "VONAL", hint: "EGYENES" },
    { category: "Színek és Formák", secretWord: "PONT", hint: "MONDAT VÉGE" },

    // 19. Kategória: Időjárás és Űr
    { category: "Időjárás és Űr", secretWord: "NAPSÜTÉS", hint: "MELEG" },
    { category: "Időjárás és Űr", secretWord: "VIHAR", hint: "VILLÁM" },
    { category: "Időjárás és Űr", secretWord: "KÖD", hint: "NEM LÁTNI" },
    { category: "Időjárás és Űr", secretWord: "JÉG", hint: "FAGY" },
    { category: "Időjárás és Űr", secretWord: "SZIVÁRVÁNY", hint: "ESŐ UTÁN SZÍNES" },
    { category: "Időjárás és Űr", secretWord: "HŐMÉRSÉKLET", hint: "CELSIUS FOK" },
    { category: "Időjárás és Űr", secretWord: "HÓESÉS", hint: "HÓEMBER" },
    { category: "Időjárás és Űr", secretWord: "NAPKILÖVELLÉS", hint: "MÁGNESES" },
    { category: "Időjárás és Űr", secretWord: "ZIVATAR", hint: "NAGY ESŐ" },
    { category: "Időjárás és Űr", secretWord: "JÉGESŐ", hint: "KOPOGÓ DARA" },
    { category: "Időjárás és Űr", secretWord: "BOLYGÓ", hint: "FÖLD" },
    { category: "Időjárás és Űr", secretWord: "ÜSTÖKÖS", hint: "CSÓVA" },
    { category: "Időjárás és Űr", secretWord: "GALAXIS", hint: "TEJÚT" },
    { category: "Időjárás és Űr", secretWord: "ŰRHAJÓS", hint: "SÚLYTALANSÁG" },
    { category: "Időjárás és Űr", secretWord: "RAKÉTA", hint: "KILÖVÉS" },
    { category: "Időjárás és Űr", secretWord: "METEOR", hint: "HULLÓCSILLAG" },
    { category: "Időjárás és Űr", secretWord: "FEKETELYUK", hint: "GRAVITÁCIÓ" },
    { category: "Időjárás és Űr", secretWord: "MARS", hint: "VÖRÖS BOLYGÓ" },
    { category: "Időjárás és Űr", secretWord: "MŰHOLD", hint: "GPS" },
    { category: "Időjárás és Űr", secretWord: "TÁVCSŐ", hint: "CSILLAGVIZSGÁLÓ" },

    // 20. Kategória: Hobbik és Szabadidő
    { category: "Hobbik és Szabadidő", secretWord: "OLVASÁS", hint: "KÖNYVEK" },
    { category: "Hobbik és Szabadidő", secretWord: "RAJZOLÁS", hint: "CERUZA" },
    { category: "Hobbik és Szabadidő", secretWord: "FESTÉS", hint: "ECSET" },
    { category: "Hobbik és Szabadidő", secretWord: "ÉNEKLÉS", hint: "HANG" },
    { category: "Hobbik és Szabadidő", secretWord: "TÁNCOLÁS", hint: "ZENE ÉS RITMUS" },
    { category: "Hobbik és Szabadidő", secretWord: "FÉNYKÉPEZÉS", hint: "OBJEKTÍV" },
    { category: "Hobbik és Szabadidő", secretWord: "KERTÉSZKEDÉS", hint: "ÜLTETÉS" },
    { category: "Hobbik és Szabadidő", secretWord: "FŐZÉS", hint: "RECEPT" },
    { category: "Hobbik és Szabadidő", secretWord: "SÜTÉS", hint: "TORTA" },
    { category: "Hobbik és Szabadidő", secretWord: "HORGÁSZAT", hint: "BOT ÉS CSALI" },
    { category: "Hobbik és Szabadidő", secretWord: "VADÁSZAT", hint: "ERDŐ" },
    { category: "Hobbik és Szabadidő", secretWord: "BÉLYEGGYŰJTÉS", hint: "ALBUM" },
    { category: "Hobbik és Szabadidő", secretWord: "KIRÁNDULÁS", hint: "TÚRABAKANCS" },
    { category: "Hobbik és Szabadidő", secretWord: "KEMPINGEZÉS", hint: "SÁTOR" },
    { category: "Hobbik és Szabadidő", secretWord: "SAKKOZÁS", hint: "TÁBLAJÁTÉK" },
    { category: "Hobbik és Szabadidő", secretWord: "VIDEÓJÁTÉK", hint: "KONZOL" },
    { category: "Hobbik és Szabadidő", secretWord: "TÁRSASJÁTÉK", hint: "DOBÓKOCKA" },
    { category: "Hobbik és Szabadidő", secretWord: "KÖTÉS", hint: "FONAL ÉS TŰ" },
    { category: "Hobbik és Szabadidő", secretWord: "BARKÁCSOLÁS", hint: "SZERSZÁMOK" },
    { category: "Hobbik és Szabadidő", secretWord: "BÚVÁRKODÁS", hint: "OXIGÉNPALACK" }
];